angular: fix karma config file
$ ng test --no-watch --no-progress --browsers=FirefoxHeadless
18 01 2020 19:35:46.434:ERROR [config]: Invalid config file!
  /home/kushal/src/angular/terlingua/web/karma.conf.js:36
  });
   ^

SyntaxError: Unexpected token ')'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.parseConfig (/home/kushal/src/angular/terlingua/web/node_modules/karma/lib/config.js:351:22)
    at new Server (/home/kushal/src/angular/terlingua/web/node_modules/karma/lib/server.js:66:24)
    at Observable._subscribe (/home/kushal/src/angular/terlingua/web/node_modules/@angular-devkit/build-angular/src/karma/index.js:100:29)
    at Observable._trySubscribe (/home/kushal/src/angular/terlingua/web/node_modules/rxjs/src/internal/Observable.ts:231:19)
    at Observable.subscribe (/home/kushal/src/angular/terlingua/web/node_modules/rxjs/src/internal/Observable.ts:212:14)
    at /home/kushal/src/angular/terlingua/web/node_modules/rxjs/src/internal/util/subscribeTo.ts:22:23
    at Object.subscribeToResult (/home/kushal/src/angular/terlingua/web/node_modules/rxjs/src/internal/util/subscribeToResult.ts:25:29)
    at SwitchMapSubscriber._innerSub (/home/kushal/src/angular/terlingua/web/node_modules/rxjs/src/internal/operators/switchMap.ts:122:30)